Upgrades project to Quartz.NET 3.x and RavenDB 5.x (.NET Framework & Core)
ravendb/quartznet-RavenDB pull request #14
Opened 2021-08-18 18:56 UTC by nefarius

Disclaimer ahead: sorry that this is so huge and probably a pain to review; I really wanted to use this in production for a project of mine so I went on ahead full throttle and migrated and modernized the entire library, example projects, tests and documentation in one go 😅 

## Changes included

Here we go:

- Compatibility raised to Quartz.NET 3.x
- Compatibility raised to RavenDB 5.x
- Migrated projects to new Visual Studio SDK format
- Added .NET Core Worker Example
- Updated README
- Adopted [TAP-Model](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/task-asynchronous-programming-model) everywhere
- Removed logging library dependency
- Optimized and reduced overall database calls
- Removed outdated indexes
- Fixed an issue deserializing `Quartz.TimeOfDay` type from JSON
- Changed serializing `JobType` without assembly version information to avoid exceptions on restoring jobs after assembly version increased (for example through use of CI)
- Added Fluent API helper methods for convenient configuration in .NET Core projects
- Removed outdated/obsolete files (NuSpec etc.)

Thanks / have fun 🙃

2021-08-23 09:24 UTC, ayende requested changes

2021-08-23 09:24 UTC, ayende commented on src/Examples/App.config
> +    <add name="quartznet-ravendb" connectionString="Url=http://live-test.ravendb.net;DefaultDatabase=QuartzDemo" />
I would recommend removing this entirely. We aren't supporting this format any longer, and to do this properly you'll need to handle certs, pass, etc.

2021-08-23 09:24 UTC, ayende commented on src/Quartz.Impl.RavenDB/RavenJobStore.IJobStore.cs
> +                ((DocumentStore) Store).Certificate = new X509Certificate2(CertPath, CertPass);
Better to put that in the init, as a conditional, no?

2021-08-23 09:24 UTC, ayende commented on src/Quartz.Impl.RavenDB/RavenJobStore.IJobStore.cs
> +                foreach (var orig in pair.Value.Where(t => t.GetType() == typeof(IOperableTrigger))
What is that? You are checking if this is a `IOperableTrigger` ? That is an interface, so it will only be matched by `IOperableTrigger`. Did you mean to do `OfType<IOperableTrigger>()`, instead?

2021-08-23 09:24 UTC, ayende commented on src/Quartz.Impl.RavenDB/RavenJobStore.IJobStore.cs
> +            catch (NullReferenceException)
That is a bug. Under what scenario do you *expect* null reference exeption here?

2021-08-23 16:10 UTC, nefarius commented on src/Examples/App.config
> +    <add name="quartznet-ravendb" connectionString="Url=http://live-test.ravendb.net;DefaultDatabase=QuartzDemo" />
Leftover indeed, will remove it.

2021-08-23 16:11 UTC, nefarius commented on src/Quartz.Impl.RavenDB/RavenJobStore.IJobStore.cs
> +            catch (NullReferenceException)
Copypasta mistake, will remove.

2021-08-23 16:11 UTC, nefarius commented on src/Quartz.Impl.RavenDB/RavenJobStore.IJobStore.cs
> +                foreach (var orig in pair.Value.Where(t => t.GetType() == typeof(IOperableTrigger))
Yikes, `OfType<IOperableTrigger>()` is ofc. the way to go!

2021-08-23 16:12 UTC, nefarius commented on src/Quartz.Impl.RavenDB/RavenJobStore.IJobStore.cs
> +                ((DocumentStore) Store).Certificate = new X509Certificate2(CertPath, CertPass);
Sorry, I'm afraid I didn't get what you meant there?

2021-08-24 10:09 UTC, ayende commented on src/Quartz.Impl.RavenDB/RavenJobStore.IJobStore.cs
> +                ((DocumentStore) Store).Certificate = new X509Certificate2(CertPath, CertPass);
```
 Store = new DocumentStore
            {
                Urls = _urls,
                Database = Database,
                Certificate = string.IsNullOrEmpty(CertPath) ? null : new X509Certificate2(CertPath, CertPass)
            };

```

2021-08-24 10:38 UTC, nefarius commented on src/Quartz.Impl.RavenDB/RavenJobStore.IJobStore.cs
> +                ((DocumentStore) Store).Certificate = new X509Certificate2(CertPath, CertPass);
Ofc., done!

2021-09-03 07:32 UTC, ayende commented
Looks great

2021-09-03 07:32 UTC, merged